import { useEffect, useState } from "react";
import { Download, Eye, FileSpreadsheet } from "lucide-react";
import api from "../services/api";

function parseCsv(text) {
  const lines = text.split(/\r?\n/).filter((line) => line.trim());
  const parseLine = (line) => { const values = []; let value = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { values.push(value.trim()); value = ""; } else value += char; } values.push(value.trim()); return values; };
  const headers = parseLine(lines[0] || []).map((header) => header.toLowerCase().replace(/[^a-z0-9_]+/g, "_"));
  return { headers, rows: lines.slice(1).map((line) => Object.fromEntries(parseLine(line).map((value, index) => [headers[index], value]))) };
}

export default function DynamicCertificateGenerator() {
  const [templates, setTemplates] = useState([]); const [templateId, setTemplateId] = useState(""); const [template, setTemplate] = useState(null); const [file, setFile] = useState(null); const [headers, setHeaders] = useState([]); const [rows, setRows] = useState([]); const [mapping, setMapping] = useState({}); const [preview, setPreview] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { api.get("/certificate-templates?activeOnly=true").then((response) => setTemplates(response.data.templates || [])).catch(() => setError("Could not load certificate templates")); }, []);
  const selectTemplate = (id) => { setTemplateId(id); setTemplate(templates.find((item) => item._id === id) || null); };
  const selectFile = (event) => { const selected = event.target.files?.[0]; if (!selected) return; setFile(selected); const reader = new FileReader(); reader.onload = () => { const parsed = parseCsv(String(reader.result)); setHeaders(parsed.headers); setRows(parsed.rows); const next = {}; (template?.fields || []).forEach((field) => { next[field.id] = parsed.headers.find((header) => header === field.id || header.includes(field.id)) || ""; }); setMapping(next); }; reader.readAsText(selected); };
  const renderPreview = async () => { setBusy(true); setError(""); try { const response = await api.post("/dynamic-certificates/preview", { templateId, data: Object.fromEntries((template.fields || []).map((field) => [field.id, rows[0]?.[mapping[field.id]] || ""])) }, { responseType: "blob" }); setPreview(URL.createObjectURL(response.data)); } catch (requestError) { setError(requestError.response?.data?.error || "Could not render preview"); } finally { setBusy(false); } };
  const generate = async () => { if (!file) return; setBusy(true); setError(""); try { const form = new FormData(); form.append("templateId", templateId); form.append("mapping", JSON.stringify(mapping)); form.append("file", file); const response = await api.post("/dynamic-certificates/generate", form, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = "certificates.zip"; link.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(requestError.response?.data?.error || "Could not generate certificates"); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-[#0d0d0d] text-white p-6 md:p-10"><div className="max-w-5xl mx-auto"><h1 className="text-3xl font-bold">Certificate Generator</h1><p className="text-[#777] mt-1 mb-8">Select an admin-created template, map a CSV, and generate certificates.</p><section className="rounded-xl border border-[#252525] bg-[#111] p-5 space-y-5"><label className="block"><span className="text-sm text-[#aaa]">Certificate template</span><select value={templateId} onChange={(event) => selectTemplate(event.target.value)} className="mt-2 w-full rounded-lg bg-[#0d0d0d] border border-[#2a2a2a] p-3"><option value="">Select a template</option>{templates.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label>{template && <><label className="flex items-center gap-2 text-[#fbbf24] cursor-pointer"><FileSpreadsheet size={18} /> Upload CSV<input type="file" accept=".csv,text/csv" onChange={selectFile} className="hidden" /></label>{file && <p className="text-sm text-[#aaa]">{file.name} · {rows.length} rows · {headers.length} columns</p>}{rows.length > 0 && <div className="space-y-3"><h2 className="font-semibold">Map CSV columns</h2>{template.fields.map((field) => <label key={field.id} className="grid md:grid-cols-[1fr_1fr] gap-2 items-center"><span>{field.label} <small className="text-[#777]">({field.id})</small></span><select value={mapping[field.id] || ""} onChange={(event) => setMapping((current) => ({ ...current, [field.id]: event.target.value }))} className="rounded-lg bg-[#0d0d0d] border border-[#2a2a2a] p-2"><option value="">Select CSV column</option>{headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}<div className="flex flex-wrap gap-3"><button onClick={renderPreview} disabled={busy || !templateId} className="flex items-center gap-2 rounded-lg bg-[#0ea5e9] px-4 py-2 font-semibold"><Eye size={17} /> Preview</button><button onClick={generate} disabled={busy || !file} className="flex items-center gap-2 rounded-lg bg-[#f59e0b] px-4 py-2 font-semibold text-black"><Download size={17} /> {busy ? "Generating..." : "Generate ZIP"}</button></div></div>}{preview && <img src={preview} alt="Certificate preview" className="max-w-full border border-[#333] bg-white" />}</>}{error && <p className="text-red-400 text-sm">{error}</p>}</section></div></main>;
}
